apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-operator
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      name: mysql-operator
  template:
    metadata:
      labels:
        name: mysql-operator
    spec:
      serviceAccountName: mysql-operator
      containers:
        - name: operator
          image: "ghcr.io/halkeye/mysql-operator:latest"
          args: [ "--zap-log-level=info" ]
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ANSIBLE_DEBUG_LOGS
              value: "True"
            - name: OPERATOR_NAME
              value: "mysql-operator"
            # - name: ANSIBLE_VERBOSITY
            #   value: "4"
          resources:
            requests:
              memory: 400Mi
            limits:
              memory: 400Mi
